### PR TITLE
 make protocol functions data type specific

### PR DESCRIPTION
**Pull request by tomerd**

### CODE REVIEW

**Comment by ktoso** [comment]
Depends on https://github.com/tomerd/swift-server-metrics-api-proposal/pull/13

**Review by ktoso — APPROVED** [review]
Looks good AFAICS. 
Rationale outlined by @weissi in https://forums.swift.org/t/feedback-server-metrics-api/21353/13?u=ktoso

**Review by Lukasa — COMMENTED** [review]
Any reason the generic extension proposal isn’t being used here?

**Comment by tomerd** [comment]
spoke with @Lukasa over the phone, the generics are still available on the concrete metrics object, and the handler protocol now uses non-generic data types, so we should be good

**Review by weissi — COMMENTED** [review]
late lgtm, awesome!

**Pull request merged**
